[package]
name = "lord"
version = "0.1.0"
authors = ["Syn-Nine <contact@syn-nine.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
console = "0.13"